### PR TITLE
[WIP] Update MetatlasObject with the new object model

### PR DESCRIPTION
**Pull request by blink1073**
@benbowen, here is an implementation of the idea I mentioned here: https://github.com/metabolite-atlas/metatlas/issues/16#issuecomment-145189773.

### CODE REVIEW

**Comment by blink1073** [comment]
Notes:

```python
def retrieve(object_type, **kwargs):
    """Get objects from the Metatlas object database.

    Parameters
    ----------
    object_type: string
      The type of object to search for (i.e. "Groups").
    **kwargs
      Specific search queries (i.e. name="Sargasso").
      Use '%' for wildcard patterns (i.e. description='Hello%').
      If you want to match a '%' character, use '%%'.

    Returns
    -------
    objects: list
      List of Metatlas Objects meeting the criteria.  Will return the
      latest version of each object.
    """
    pass


def store(objects):
    """Store Metatlas objects in the database.

    Parameters
    ----------
    objects: Metatlas object or list of Metatlas Objects
        Object(s) to store in the database.
    """
    pass


def clone(objects):
    """Store Metatlas objects in the database.

    Parameters
    ----------
    objects: Metatlas object or list of Metatlas Objects
        Object(s) to clone.
    """
    pass

```

All of these methods will batch the queries, and then execute all at once

**Comment by blink1073** [comment]
Those three functions will replace `queryDatabase`, `MetatlasObject.store`, `MetatlasObject.clone`, and `MetatlasObject.retreive`.

**Comment by blink1073** [comment]
Initial implementation is done, need to update the tests.

**Comment by blink1073** [comment]
We're going to have to nuke the database and start over once I push this.

**Comment by benbowen** [comment]
go for it.  Pete is our pre-alpha tester and I've warned him that this will
happen.

**Pull request merged**
